In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
file=pd.read_csv("creditcard.csv")

In [3]:
file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [4]:
file.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [5]:
file.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
file['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [7]:
normal=file[file.Class==0]

In [8]:
fraud=file[file.Class==1]

In [9]:
print(normal.shape)

(284315, 31)

In [10]:
print(normal.shape)

(284315, 31)

In [11]:
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [14]:
normal_sample=normal.sample(n=492)

In [15]:
new_file=pd.concat([normal_sample,fraud],axis=0)

In [16]:
new_file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
90250,62937.0,-1.146008,1.315116,1.286894,0.705222,-0.082088,-0.016580,0.344300,0.228287,-0.594037,...,0.196101,0.460420,0.007355,0.197042,-0.418986,-0.490072,-0.661438,-0.127785,9.56,0
265137,161755.0,-0.171300,0.916223,-0.814419,-1.100307,2.015799,-0.108503,1.589433,-0.204325,-0.784630,...,0.230044,0.738430,-0.499385,-0.284957,0.417110,-0.135669,0.105199,0.143315,18.06,0
34990,37910.0,1.186109,0.078741,0.356617,0.452773,-0.315320,-0.474812,-0.031300,-0.027282,-0.149221,...,-0.214021,-0.732957,0.061690,-0.014428,0.211132,0.095781,-0.040623,0.009725,29.99,0
107916,70676.0,0.899465,-0.885293,0.979371,0.122642,-0.963918,0.887041,-0.866304,0.521578,1.102701,...,-0.082748,-0.213168,0.059821,-0.227101,-0.114972,0.977904,-0.029646,0.011258,102.14,0
77937,57288.0,-1.102829,0.904073,2.083212,1.456899,0.657270,1.083397,0.318322,0.481334,-0.794226,...,0.079519,0.228566,-0.272630,-0.294100,0.490725,0.015723,-0.296399,-0.014614,1.64,0
155682,106103.0,-0.565214,0.959295,2.204687,-0.111557,-0.013852,-0.207284,0.405424,-0.050284,1.320794,...,-0.252371,-0.423860,-0.259496,-0.180510,0.296629,-0.693236,0.087458,0.076223,11.27,0
139521,83189.0,-2.957914,-4.267616,2.122701,-0.809990,1.448666,-0.320048,-2.390253,0.770526,-2.210935,...,0.506660,0.686935,0.993696,-0.679217,0.013191,0.134819,-0.005766,0.145102,218.00,0
48553,43693.0,-2.220855,-1.283315,1.013194,-1.962033,-2.023941,-0.954031,0.077414,0.011224,-2.294701,...,-0.359968,-0.576637,-0.336343,0.743286,-0.281030,-0.589494,0.333959,-0.190219,285.70,0
213514,139285.0,1.964299,-1.250643,-0.782279,-1.352740,-0.422983,1.110736,-1.214942,0.442866,-0.268274,...,-0.475888,-0.911537,0.524517,-1.669649,-1.116122,0.970320,-0.030354,-0.069905,41.65,0
261896,160231.0,0.020938,0.703736,0.119410,-0.777879,0.532055,-0.600869,0.830592,0.033937,-0.090427,...,-0.246358,-0.632971,0.033640,-0.448039,-0.507737,0.149057,0.233273,0.080914,7.26,0

In [17]:
new_file['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [18]:
new_file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95325.971545,-0.162915,-0.054581,0.012682,0.006445,0.068585,-0.147456,-0.003381,0.024799,-0.003819,...,-0.014548,0.024902,-0.009712,0.016087,-0.010398,0.002704,0.005341,-0.024983,0.013049,77.043374
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [19]:
X=new_file.drop(columns='Class',axis=1)

In [20]:
Y=new_file['Class']

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [22]:
model=LogisticRegression()

In [23]:
model.fit(X_train,Y_train)

LogisticRegression()

In [24]:
X_train_prediction=model.predict(X_train)

In [25]:
training_data_acuracy=accuracy_score(X_train_prediction,Y_train)*100

In [26]:
print(f"Training Data Accuracy: {training_data_acuracy}%")

Training Data Accuracy: 93.7738246505718%

In [27]:
X_test_prediction=model.predict(X_test)

In [28]:
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)*100

In [29]:
print(f"Test Data Accuracy: {test_data_accuracy}%")

Test Data Accuracy: 92.89340101522842%